services:
    meshtasticd:
        ## The container_name should be unique for each instance of the container.
        container_name: meshtasticd_node1
        image: meshtastic/meshtasticd:daily-alpine
        stdin_open: true
        tty: true
        network_mode: "host"
        restart: unless-stopped
        devices:
            ## Uncomment the lines you need for the specific hardware you want to pass through
            ## Pass through the USB device (hint: use `lsusb` to find the correct device path (look for `QinHeng Electronics CH341 in EPP/MEM/I2C mode, EPP/I2C adapter`)
            - /dev/bus/usb/001/003 #Use `lsusb` to find the correct device path for your MeshToad, MeshStick, etc.,
            ## Pass through the main SPI bus
            #- /dev/spidev0.0:/dev/spidev0.0
            ## Pass through the GPIO controller chips for pin signaling
            #- /dev/gpiochip0:/dev/gpiochip0
            #- /dev/gpiochip4:/dev/gpiochip4 # Include extra chips if on Pi 5 / alternative boards
            ## Pass through the I2C bus
            #- /dev/i2c-1:/dev/i2c-1
            ## Pass through the serial port
            #- /dev/ttyS0:/dev/ttyS0
        volumes:
            - ./config.yaml:/etc/meshtasticd/config.yaml:ro
            - ./config.d:/etc/meshtasticd/config.d:ro
            - ./data:/var/lib/meshtasticd

